"""add_auth

Revision ID: 424a030dc976
Revises: bd4262fb9976
Create Date: 2023-08-28 22:11:13.659413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424a030dc976'
down_revision: Union[str, None] = 'bd4262fb9976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.String(), nullable=True))
    op.add_column('user', sa.Column('password_hashed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hashed')
    op.drop_column('user', 'login')
    # ### end Alembic commands ###
