"""fixed_registy_columb

Revision ID: b1823ea5a861
Revises: 63f4519660c4
Create Date: 2023-08-29 23:28:13.547587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1823ea5a861'
down_revision: Union[str, None] = '63f4519660c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_registry_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_registry_key', 'user', ['registry'])
    # ### end Alembic commands ###
