apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app.kubernetes.io/name: FinoDays
    app.kubernetes.io/component: service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: FinoDays
    app.kubernetes.io/component: service
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http